# Generated by Django 2.0.4 on 2018-04-14 22:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_type', models.TextField(choices=[('PO', 'poo'), ('BR', 'beer')], help_text='This field determines the kind of feeling of a buddy about a content.', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Buddy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social_network.Content')),
            ],
            bases=('social_network.content',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social_network.Content')),
            ],
            bases=('social_network.content',),
        ),
        migrations.AddField(
            model_name='feeling',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_ids', to='social_network.Buddy'),
        ),
        migrations.AddField(
            model_name='feeling',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_ids', to='social_network.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.Buddy', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='buddyextension',
            name='buddy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='social_network.Buddy'),
        ),
        migrations.AddField(
            model_name='buddyextension',
            name='buddy_ids',
            field=models.ManyToManyField(blank=True, to='social_network.Buddy'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_ids', to='social_network.Content'),
        ),
    ]
