# Generated by Django 2.0.4 on 2018-04-12 13:06

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Buddy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='buddyextension',
            name='buddy_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='social_network.Buddy'),
        ),
        migrations.AddField(
            model_name='buddyextension',
            name='buddy_ids',
            field=models.ManyToManyField(to='social_network.Buddy'),
        ),
    ]
