# Generated by Django 2.0.4 on 2018-04-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_type', models.TextField(choices=[('PO', 'poo'), ('BR', 'beer')], help_text='This field determines the kind of feeling of a buddy about a content.', max_length=2)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_ids', to='social_network.Buddy')),
            ],
        ),
        migrations.RenameField(
            model_name='buddyextension',
            old_name='buddy_id',
            new_name='buddy',
        ),
        migrations.AlterField(
            model_name='buddyextension',
            name='buddy_ids',
            field=models.ManyToManyField(blank=True, to='social_network.Buddy'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social_network.Content')),
            ],
            bases=('social_network.content',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social_network.Content')),
            ],
            bases=('social_network.content',),
        ),
        migrations.AddField(
            model_name='feeling',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_ids', to='social_network.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.Buddy', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_ids', to='social_network.Content'),
        ),
    ]
